name: Django CI/CD Master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linting
        run: flake8

      - name: Run tests with pytest
        env:
          SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DEBUG: 0
        run: pytest

      - name: Run Django tests
        run: python manage.py test

      - name: Run tests with coverage
        run: |
          coverage run --omit=*/tests.py manage.py test

      - name: Check test coverage
        run: coverage report --fail-under=80


